# This workflow will build a middleman project with bundle

name: Testing For PRs

on: [ pull_request ]

env:
  RUN_EXTERNAL_CHECKS: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true # would run bundle install
      - name: Run the build
        run: bundle exec rake complete_build
